#tabuada de um número inteiro qualquer

numero = int(input("Digite um número inteiro"))

print("-"*12)
print(numero, "X 0 = " ,numero * 0)
print(numero, "X 1 = " ,numero * 1)
print(numero, "X 2 = " ,numero * 2)
print(numero, "X 3 = " ,numero * 3)
print(numero, "X 4 = " ,numero * 4)
print(numero, "X 5 = " ,numero * 5)
print(numero, "X 6 = " ,numero * 6)
print(numero, "X 7 = " ,numero * 7)
print(numero, "X 8 = " ,numero * 8)
print(numero, "X 9 = " ,numero * 9)
print(numero, "X 10 = " ,numero * 10)
print("-"*12)

print('{} x {:2} = {}'. format(numero,1,numero*1))
print('{} x {:2} = {}'. format(numero,2,numero*2))
print('{} x {:2} = {}'. format(numero,3,numero*3))
print('{} x {:2} = {}'. format(numero,4,numero*4))
print('{} x {:2} = {}'. format(numero,5,numero*5))
print('{} x {:2} = {}'. format(numero,6,numero*6))
print('{} x {:2} = {}'. format(numero,7,numero*7))
print('{} x {:2} = {}'. format(numero,8,numero*8))
print('{} x {:2} = {}'. format(numero,9,numero*9))
print('{} x {:2} = {}'. format(numero,10,numero*10))
print("-"*12)